name: Update Terraform documentation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  terraform-docs:
    uses: weiiwang01/operator-workflows/.github/workflows/generate_terraform_docs.yaml@terraform-docs
    secrets: inherit
    with:
      terraform-directory: terraform/charm,terraform/product,terraform/product/modules/traefik-k8s
